Update rebuild

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -922,6 +922,27 @@ refactor_bootfs() {
         sed -i "s|meson.*.dtb|${FDTFILE}|g" ${boot_extlinux_file}
         sed -i "s|sun.*.dtb|${FDTFILE}|g" ${boot_extlinux_file}
         sed -i "s|rk.*.dtb|${FDTFILE}|g" ${boot_extlinux_file}
+
+        echo "customize oec boot files..."
+        if [ "${make_openwrt[0]}" = "wxy-oect" ]; then
+            sed -i "s|FDT\s*/dtb/rockchip/rk.*\.dtb|FDT /dtb/rockchip/rk3566-oec-box-wxy4.dtb|g" "${boot_extlinux_file}"
+            dtb_source_dir="${tag_bootfs}/dtb/${PLATFORM}"
+            mkdir -p ${tag_bootfs}/boot/dtb/${PLATFORM}
+            # 2. 查找并复制包含"oec"的DTB文件
+            find "${dtb_source_dir}" -type f -name '*oec*.dtb' -print0 | while IFS= read -r -d $'\0' src_dtb; do
+                # 复制文件并重命名
+                cp -v "${src_dtb}" "${tag_bootfs}/boot/dtb/${PLATFORM}/rk3566-oec-box-wxy4.dtb"
+                cp -v "${src_dtb}" "${tag_bootfs}/dtb/${PLATFORM}/rk3566-oec-box-wxy4.dtb"
+                break  # 只处理第一个匹配文件（若需全部复制则删除此行）
+            done
+            # 3. 验证文件是否复制成功
+            if [[ ! -f "${tag_bootfs}/boot/dtb/${PLATFORM}/rk3566-oec-box-wxy4.dtb" ]]; then
+                echo "ERROR: Target DTB file not found!"
+                exit 1
+            fi
+        fi
+        echo "customize oec boot files done"
+
         # If needed, such as t95z(s905x), rename delete .bak
         [[ "${BOOT_CONF}" == "extlinux.conf" ]] && mv -f ${boot_extlinux_file} ${rename_extlinux_file}
     }
